<script setup lang="ts">
import { NbBadge, NbCard, NbLink, NbSeparator } from '@neobrut-vue/core'
import { NuxtLink } from '#components'

useSeoMeta({
  title: 'About — avrdu.de',
  description: 'About avrdu and this little corner of the web.',
})
</script>

<template>
  <div class="simple-page page-section">
    <h1 class="display-title">about.</h1>
    <p class="simple-page__lede">A developer who builds things for the web and writes them down before the details disappear.</p>
    <NbSeparator />

    <div class="about-grid">
      <div class="article-copy">
        <p>I like simple tools, fast sites, and writing things down so I don't forget them later.</p>
        <p>This site is where I put posts, TILs, and project notes. It is built with Nuxt, generated into static files, and deployed on Cloudflare Pages. No server is waiting behind the page.</p>
        <p>If something is broken, there is a nonzero chance it was generated by an AI that hallucinated the fix. <NbLink :as="NuxtLink" to="/posts/hello-world/">I wrote about that.</NbLink></p>
        <h2>Elsewhere</h2>
        <ul>
          <li><NbLink href="https://github.com/avr6ude" target="_blank" rel="noopener">GitHub ↗</NbLink></li>
          <li><NbLink href="https://www.linkedin.com/in/avrdude/" target="_blank" rel="noopener">LinkedIn ↗</NbLink></li>
          <li><NbLink href="https://t.me/avrdudec" target="_blank" rel="noopener">Telegram ↗</NbLink></li>
        </ul>
      </div>

      <NbCard tone="secondary" class="about-card">
        <template #header><NbBadge tone="primary" size="sm">STACK NOTE</NbBadge></template>
        <p>Markdown in. Static HTML out. Loud components in the middle.</p>
        <p class="about-card__mono">nuxt / vue / neobrut-vue / cloudflare pages</p>
      </NbCard>
    </div>
  </div>
</template>

<style scoped>
.simple-page { max-width: 64rem; margin: 0 auto; }
.simple-page__lede { max-width: 40ch; margin: 2rem 0 3rem; font-size: 1.35rem; line-height: 1.45; }
.about-grid { display: grid; grid-template-columns: minmax(0, 1fr) 18rem; gap: 4rem; align-items: start; }
.about-card { transform: rotate(-2deg); }
.about-card p { line-height: 1.5; }
.about-card__mono { font-family: var(--nb-font-mono); font-size: 0.75rem; font-weight: 700; }
.article-copy h2 { margin-top: 3rem; }
.article-copy ul { padding-left: 1.2rem; }
@media (max-width: 760px) { .about-grid { grid-template-columns: 1fr; gap: 2rem; } .about-card { max-width: 22rem; margin-left: auto; } }
@media (max-width: 700px) { .simple-page__lede { margin: 1.25rem 0 2rem; font-size: 1.05rem; } }
</style>
