<script setup lang="ts">
import { NbBadge, NbCard, NbLink, NbSeparator } from '@neobrut-vue/core'
import { NuxtLink } from '#components'

useSeoMeta({
  title: 'About — avrdu.de',
  description: 'About avrdu and this little corner of the web.',
})
</script>

<template>
  <div class="simple-page page-section">
    <h1 class="display-title">about.</h1>
    <p class="simple-page__lede">A developer who builds things for the web and writes them down before the details disappear.</p>
    <NbSeparator />

    <div class="about-grid">
      <div class="article-copy">
        <p>I like simple tools, fast sites, and writing things down so I don't forget them later.</p>
        <p>This site is where I put posts, TILs, and project notes. It is built with Nuxt, generated into static files, and deployed on Cloudflare Pages. No server is waiting behind the page.</p>
        <p>If something is broken, there is a nonzero chance it was generated by an AI that hallucinated the fix. <NbLink :as="NuxtLink" to="/posts/hello-world/">I wrote about that.</NbLink></p>
        <h2>Elsewhere</h2>
        <ul>
          <li><NbLink href="https://github.com/avr6ude" target="_blank" rel="noopener">GitHub ↗</NbLink></li>
          <li><NbLink href="https://www.linkedin.com/in/avrdude/" target="_blank" rel="noopener">LinkedIn ↗</NbLink></li>
          <li><NbLink href="https://t.me/avrdudec" target="_blank" rel="noopener">Telegram ↗</NbLink></li>
        </ul>
      </div>

      <NbCard tone="secondary" class="about-card">
        <template #header><NbBadge tone="primary" size="sm">STACK NOTE</NbBadge></template>
        <p>Markdown in. Static HTML out. Loud components in the middle.</p>
        <p class="about-card__mono">nuxt / vue / neobrut-vue / cloudflare pages</p>
      </NbCard>
    </div>
  </div>
</template>

<style scoped>
.simple-page { max-width: var(--site-size-content); margin: 0 auto; }
.simple-page__lede { max-width: 40ch; margin: var(--site-space-8) 0 var(--site-space-12); font-size: var(--site-font-about); line-height: var(--site-leading-copy); }
.about-grid { display: grid; grid-template-columns: minmax(0, 1fr) var(--site-size-sidebar); gap: var(--site-space-16); align-items: start; }
.about-card { transform: rotate(-2deg); }
.about-card p { line-height: var(--site-leading-body); }
.about-card__mono { font-family: var(--nb-font-mono); font-size: var(--site-font-meta); font-weight: var(--site-weight-strong); }
.article-copy h2 { margin-top: var(--site-space-12); }
.article-copy ul { padding-left: var(--site-space-5); }
@media (max-width: 760px) { .about-grid { grid-template-columns: 1fr; gap: var(--site-space-8); } .about-card { max-width: var(--site-size-card-narrow); margin-left: auto; } }
@media (max-width: 700px) { .simple-page__lede { margin: var(--site-space-5) 0 var(--site-space-8); font-size: var(--site-font-body-lg); } }
</style>
